sync:
	rm -f ../../rof/ecommons*
	cp ecommons_chr.s3d ../../rof/ecommons_chr.s3d
	cp ecommons_chr.txt ../../rof/ecommons_chr.txt
	cp ecommons_obj.s3d ../../rof/ecommons_obj.s3d
	cp ecommons_sndbnk.eff ../../rof/ecommons_sndbnk.eff
	cp ecommons_sounds.eff ../../rof/ecommons_sounds.eff
	cp ecommons.s3d ../../rof/ecommons.s3d