rm -f ../../rof/bazaar*
cp bazaar_assets.txt ../../rof/
cp bazaar_chr.s3d ../../rof/
cp bazaar_chr.wld.txc ../../rof/
cp bazaar_EnvironmentEmitters.txt ../../rof/
cp bazaar_obj.s3d ../../rof/
cp bazaar_obj.wld.txc ../../rof/
cp bazaar.s3d ../../rof/
cp bazaar.txt ../../rof/maps/
cp bazaar.wld.txc ../../rof/