sync:
	rm -f ../../rof/bazaar*
	cp bazaar_assets.txt ../../rof/bazaar_assets.txt
	cp bazaar_chr.s3d ../../rof/bazaar_chr.s3d
	cp bazaar_chr.wld.txc ../../rof/bazaar_chr.wld.txc
	cp bazaar_EnvironmentEmitters.txt ../../rof/bazaar_EnvironmentEmitters.txt
	cp bazaar_obj.s3d ../../rof/bazaar_obj.s3d
	cp bazaar_obj.wld.txc ../../rof/bazaar_obj.wld.txc
	cp bazaar.s3d ../../rof/bazaar.s3d
	cp bazaar.wld.txc ../../rof/bazaar.wld.txc