rm -f ../../rof/nektulos*
cp nektulos_assets.txt ../../rof/
cp nektulos_chr.s3d ../../rof/
cp nektulos_chr.txt ../../rof/
cp nektulos_EnvironmentEmitters.txt ../../rof/
cp nektulos_obj.s3d ../../rof/
cp nektulos_obj1.eqg ../../rof/
cp nektulos_sndbnk.eff ../../rof/
cp nektulos_sounds.eff ../../rof/
cp nektulos.emt ../../rof/
cp nektulos.eqg ../../rof/
cp nektulos.mp3 ../../rof/
cp nektulos.s3d ../../rof/
cp nektulos.xmi ../../rof/
cp nektulos.zon ../../server/