sync:
	rm -f ../../rof/highpass*
	cp highpass_chr.s3d ../../rof/highpass_chr.s3d
	cp highpass_obj.s3d ../../rof/highpass_obj.s3d
	cp highpass_sndbnk.eff ../../rof/highpass_sndbnk.eff
	cp highpass_sounds.eff ../../rof/highpass_sounds.eff
	cp highpass.s3d ../../rof/highpass.s3d