sync:
	rm -f ../../rof/nektulos*
	cp nektulos_chr.s3d ../../rof/nektulos_chr.s3d
	cp nektulos_obj.s3d ../../rof/nektulos_obj.s3d
	cp nektulos_obj1.eqg ../../rof/nektulos_obj1.eqg
	cp nektulos_sndbnk.eff ../../rof/nektulos_sndbnk.eff
	cp nektulos_sounds.eff ../../rof/nektulos_sounds.eff
	cp nektulos.emt ../../rof/nektulos.emt
	cp nektulos.mp3 ../../rof/nektulos.mp3
	cp nektulos.s3d ../../rof/nektulos.s3d
	cp nektulos.xmi ../../rof/nektulos.xmi
	cp Nektulos.zon ../../server/Nektulos.zon