rm -f ../../rof/lavastorm*
cp lavastorm_chr.s3d ../../rof/lavastorm_chr.s3d
cp lavastorm_chr.txt ../../rof/lavastorm_chr.txt
cp lavastorm_EnvironmentEmitters.txt ../../rof/lavastorm_EnvironmentEmitters.txt
cp lavastorm_obj.s3d ../../rof/lavastorm_obj.s3d
cp lavastorm_sndbnk.eff ../../rof/lavastorm_sndbnk.eff
cp lavastorm_sounds.eff ../../rof/lavastorm_sounds.eff
cp lavastorm.emt ../../rof/lavastorm.emt
cp lavastorm.mp3 ../../rof/lavastorm.mp3
cp lavastorm.s3d ../../rof/lavastorm.s3d