sync:
	rm -f ../../rof/barter*
	cp guildhall_assets.txt ../../rof/
	cp guildhall_EnvironmentEmitters.txt ../../rof/
	cp guildhall.eqg ../../rof/
	cp GuildHall.mp3 ../../rof/
	cp guildhall.txt ../../rof/maps/