rm -f ../../rof/lavastorm*
cp lavastorm_chr.s3d ../../rof/
cp lavastorm_chr.txt ../../rof/maps/
cp lavastorm_EnvironmentEmitters.txt ../../rof/
cp lavastorm_obj.s3d ../../rof/
cp lavastorm_sndbnk.eff ../../rof/
cp lavastorm_sounds.eff ../../rof/
cp lavastorm.emt ../../rof/
cp lavastorm.eqg ../../rof/
cp lavastorm.mp3 ../../rof/
cp lavastorm.s3d ../../rof/
cp lavastorm.xmi ../../rof/